version: '3'

services:
  img_to_art_postgres:
    container_name: img_to_art_postgres
    image: postgres:15.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

  img_to_art_backend:
    container_name: img_to_art_backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
      - /home/imgtoart/ssl:/etc/certs
    depends_on:
      - img_to_art_postgres
    env_file:
      - .env
    restart: always

  img_to_art_frontend:
    container_name: img_to_art_frontend
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - /home/imgtoart/ssl:/etc/certs
    depends_on:
      - img_to_art_backend
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env
    restart: always
